### ISSUE TITLE
Master doesn't compile

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#979]
The following line doesn't compile on gcc-4.8.

https://github.com/NCAR/VAPOR/blob/dbfa0188eae3834de7c527045f8c16f12bf38c08/lib/render/BarbRenderer.cpp#L851

Test machine: Geyser. 
Error: [ 59%] /glade/u/home/shaomeng/Git/VAPOR-git-src/lib/render/BarbRenderer.cpp: In member function 'void VAPoR::BarbRenderer::_getMagnitudeAtPoint(std::vector<VAPoR::Grid*>, float*)':
/glade/u/home/shaomeng/Git/VAPOR-git-src/lib/render/BarbRenderer.cpp:851:16: error: call of overloaded 'isnan(double&)' is ambiguous
    !isnan(value))
