### ISSUE TITLE
Python API fails to build on Mac.

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3117]
The Python API fails to build on my Mac, OSX 11.6 (Xcode 13.2):

```
[ 52%] Building CXX object lib/render/CMakeFiles/render.dir/MyPython.cpp.o
/Users/clyne/src/vapor/lib/render/MyPython.cpp:242:25: error: use of undeclared identifier 'PyUnicode_AsUTF8'
    const char *    s = PyUnicode_AsUTF8(output);
                        ^
/Users/clyne/src/vapor/lib/render/MyPython.cpp:265:25: error: use of undeclared identifier 'PyUnicode_AsUTF8'
    const char *    s = PyUnicode_AsUTF8(output);
                        ^
2 errors generated.

```

Note, when I configure with cmake I'm enabling BUILD_PYTHON, and disabling BUILD_GUI. After typing 'c' in cmake I get the output below, which would suggest that the build is finding Apple's bundled 2.x python distro, not the one that is in VAPOR-Deps/2019-Aug?

 Python Found
 Python_VERSION = '2.7.16'
 Python_NumPy_VERSION = '1.8.0rc1'
 Python_LIBRARIES =
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dyl
 ib' OK
 Python_INCLUDE_DIRS =
 '/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7'
 OK
 Python_SITELIB = '/Library/Python/2.7/site-packages' OK
 Python_NumPy_INCLUDE_DIRS =
 '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/nu
 mpy/core/include' OK
 Python Found: '2.7.16'
 (/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dyl
 ib)

**Comment by sgpearse** [comment]
@pearse will try to reproduce.

**Comment by sgpearse** [comment]
I see the same error on my OSX 11.6 machine, using XCode 13.2.1.

CMake issues the following which indicates that it's correctly finding our bundled version of Python 3.6.

> -- The C compiler identification is AppleClang 13.0.0.13000029
> -- The CXX compiler identification is AppleClang 13.0.0.13000029
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> Using bundled python
> Python Found
> 	Python_VERSION = '3.6'
> 	Python_NumPy_VERSION = 'UNUSED IN BUNDLED PYTHON'
> 	Python_LIBRARIES = '/usr/local/VAPOR-Deps/2019-Aug/lib/libpython3.6m.dylib' OK
> 	Python_INCLUDE_DIRS = '/usr/local/VAPOR-Deps/2019-Aug/include/python3.6m' OK
> 	Python_SITELIB = '/usr/local/VAPOR-Deps/2019-Aug/lib/python3.6/site-packages' OK
> 	Python_NumPy_INCLUDE_DIRS = '/usr/local/VAPOR-Deps/2019-Aug/lib/python3.6/site-packages/numpy/core/include' OK
> -- Found Doxygen: /usr/local/bin/doxygen (found version "1.9.3") found components: doxygen dot
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/pearse/VAPOR/build
